using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GameVolumeHandler.Tools
{
    public class KeysEnum
    {
        public enum USKeys
        {
            None = 0,
            Backspace = Keys.Back,
            Tab = Keys.Tab,
            Enter = Keys.Enter,
            Shift = Keys.ShiftKey,
            Control = Keys.ControlKey,
            Alt = Keys.Menu,
            Pause = Keys.Pause,
            CapsLock = Keys.CapsLock,
            Escape = Keys.Escape,
            Space = Keys.Space,
            PageUp = Keys.PageUp,
            PageDown = Keys.PageDown,
            End = Keys.End,
            Home = Keys.Home,
            LeftArrow = Keys.Left,
            UpArrow = Keys.Up,
            RightArrow = Keys.Right,
            DownArrow = Keys.Down,
            Insert = Keys.Insert,
            Delete = Keys.Delete,
            D0 = Keys.D0,
            D1 = Keys.D1,
            D2 = Keys.D2,
            D3 = Keys.D3,
            D4 = Keys.D4,
            D5 = Keys.D5,
            D6 = Keys.D6,
            D7 = Keys.D7,
            D8 = Keys.D8,
            D9 = Keys.D9,
            A = Keys.A,
            B = Keys.B,
            C = Keys.C,
            D = Keys.D,
            E = Keys.E,
            F = Keys.F,
            G = Keys.G,
            H = Keys.H,
            I = Keys.I,
            J = Keys.J,
            K = Keys.K,
            L = Keys.L,
            M = Keys.M,
            N = Keys.N,
            O = Keys.O,
            P = Keys.P,
            Q = Keys.Q,
            R = Keys.R,
            S = Keys.S,
            T = Keys.T,
            U = Keys.U,
            V = Keys.V,
            W = Keys.W,
            X = Keys.X,
            Y = Keys.Y,
            Z = Keys.Z,
            F1 = Keys.F1,
            F2 = Keys.F2,
            F3 = Keys.F3,
            F4 = Keys.F4,
            F5 = Keys.F5,
            F6 = Keys.F6,
            F7 = Keys.F7,
            F8 = Keys.F8,
            F9 = Keys.F9,
            F10 = Keys.F10,
            F11 = Keys.F11,
            F12 = Keys.F12,
            NumLock = Keys.NumLock,
            ScrollLock = Keys.Scroll,
            Add = Keys.Add,
            Subtract = Keys.Subtract,
            Multiply = Keys.Multiply,
            Divide = Keys.Divide,
            Decimal = Keys.Decimal,
            Separator = Keys.Separator,
            Oem1 = Keys.Oem1,
            Oem2 = Keys.Oem2,
            Oem3 = Keys.Oem3,
            Oem4 = Keys.Oem4,
            Oem5 = Keys.Oem5,
            Oem6 = Keys.Oem6,
            Oem7 = Keys.Oem7,
            Oem8 = Keys.Oem8,
            OemPeriod = Keys.OemPeriod,
            OemComma = Keys.Oemcomma,
            OemMinus = Keys.OemMinus,
            OemPlus = Keys.Oemplus
        }
    }
}
